# Generated by Django 4.0.5 on 2022-06-20 13:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('byggid', models.BigIntegerField(blank=True, null=True, verbose_name='Building ID')),
                ('bygningsnr', models.BigIntegerField(blank=True, null=True, verbose_name='Building No')),
                ('bebygdarea', models.BigIntegerField(blank=True, null=True, verbose_name='Build-area(sqm)')),
                ('bygningsty', models.BigIntegerField(blank=True, null=True, verbose_name='Building type code')),
                ('bygnings_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Building type')),
                ('kommunenav', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kommune Name')),
                ('fylkesnavn', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country Name')),
                ('matrikkeln', models.CharField(blank=True, max_length=255, null=True, verbose_name='Matrikkel No')),
                ('lagretbere', models.FloatField(blank=True, null=True, verbose_name='Plot Area')),
                ('lokalid', models.BigIntegerField(blank=True, null=True, verbose_name='Local ID(plot)')),
                ('flood_Dept', models.FloatField(blank=True, null=True, verbose_name='Max Flood depth')),
                ('basement', models.BigIntegerField(blank=True, null=True, verbose_name='Basement(Y/N)')),
                ('S_drponds', models.CharField(blank=True, max_length=255, null=True, verbose_name='Suitability DR ponds')),
                ('S_filterst', models.CharField(blank=True, max_length=255, null=True, verbose_name='Suitability filter strips')),
                ('S_filterdr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Suitability filter drains')),
                ('S_dryswale', models.CharField(blank=True, max_length=255, null=True, verbose_name='Suitability dry swale')),
                ('S_permpave', models.CharField(blank=True, max_length=255, null=True, verbose_name='Suitability permeable pavements')),
                ('S_filtertr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Suitability filter strips tr')),
                ('S_raingard', models.CharField(blank=True, max_length=255, null=True, verbose_name='Suitability rain gardens')),
                ('S_RWH', models.CharField(blank=True, max_length=255, null=True, verbose_name='Suitability rainwater harvesting')),
                ('S_greenroo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Suitability greenroo')),
                ('S_infilttr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Suitability infiltration trench')),
                ('S_infilbas', models.CharField(blank=True, max_length=255, null=True, verbose_name='Suitability infiltration basin')),
                ('S_soakaway', models.CharField(blank=True, max_length=255, null=True, verbose_name='Suitability soakaway')),
                ('S_swdettan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Suitability_Stormwater detention tank')),
                ('SGM_drypro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Suitability (grey measures)_Dryproofing')),
                ('SGM_wetpro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Suitability (grey measures)_Wetproofing')),
                ('SGM_pumpsu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Suitability (grey measures)_Pumpsump')),
                ('SGM_sandba', models.CharField(blank=True, max_length=255, null=True, verbose_name='Suitability (grey measures)_Sandbagging')),
                ('SGM_fdoor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Suitability (grey measures)_Flood doors')),
                ('SGM_airbri', models.CharField(blank=True, max_length=255, null=True, verbose_name='Suitability (grey measures)_Airbrick covers')),
                ('SGM_NRvalv', models.CharField(blank=True, max_length=255, null=True, verbose_name='Suitability (grey measures)_Non-return valves')),
                ('rx_3h_2010', models.BigIntegerField(blank=True, null=True, verbose_name='Max 3h precipitation 2010')),
                ('rx_3h_2030', models.BigIntegerField(blank=True, null=True, verbose_name='Max 3h precipitation 2030')),
                ('rx_3h_2050', models.BigIntegerField(blank=True, null=True, verbose_name='Max 3h precipitation 2050')),
                ('rx_1d_2010', models.BigIntegerField(blank=True, null=True, verbose_name='Max 1d precipitation 2010')),
                ('rx_1d_2030', models.BigIntegerField(blank=True, null=True, verbose_name='Max 1d precipitation 2030')),
                ('rx_1d_2050', models.BigIntegerField(blank=True, null=True, verbose_name='Max 1d precipitation 2050')),
                ('rx_5d_2010', models.BigIntegerField(blank=True, null=True, verbose_name='Max 5d precipitation 2010')),
                ('rx_5d_2030', models.BigIntegerField(blank=True, null=True, verbose_name='Max 5d precipitation 2030')),
                ('rx_5d_2050', models.BigIntegerField(blank=True, null=True, verbose_name='Max 5d precipitation 2050')),
                ('Label', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4269)),
                ('Shape_Leng', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4269)),
                ('Shape_Area', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4269)),
            ],
        ),
    ]
